name: Delete File

on:
  workflow_dispatch: # Позволяет запускать вручную

jobs:
  delete_file_job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Delete push_swap file
      run: |
        git rm push_swap
        git commit -m "Delete push_swap via GitHub Actions"
        git push
